version: '3.9'

services:
  mongodb:
    image: mongo:8
    container_name: local-mongodb-avo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: local-mongo-express
    restart: always
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - '8084:8081' # Mongo Express UI will be available on http://localhost:8081

  app:
    image: node:22-alpine
    container_name: avo-node-app
    working_dir: /app
    depends_on:
      - mongodb
    environment:
      MONGO_URI: 'mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin'
      PORT: ${PORT}
      NODE_ENV: development
    ports:
      - '${PORT}:${PORT}'
    command: ['sh', '-c', 'npm install && npm run dev']
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules

volumes:
  mongo_data:
